"""empty message

Revision ID: 99afdc9577fe
Revises: 
Create Date: 2020-05-23 21:08:13.487346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99afdc9577fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=500), nullable=False),
    sa.Column('course_param', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('course_param')
    )
    op.create_table('nonceverify',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eth_address', sa.String(length=1000), nullable=False),
    sa.Column('nonce', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('eth_address')
    )
    op.create_table('pool',
    sa.Column('pool_subscription_id', sa.Integer(), nullable=False),
    sa.Column('pool_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('pool_buy_in_start', sa.DateTime(), nullable=True),
    sa.Column('pool_buy_in_end', sa.DateTime(), nullable=True),
    sa.Column('pool_maturity_end', sa.DateTime(), nullable=True),
    sa.Column('stake', sa.Integer(), nullable=True),
    sa.Column('donated_amount', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('pool_subscription_id', 'pool_id')
    )
    op.create_table('student',
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('public_address', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('student_id'),
    sa.UniqueConstraint('public_address')
    )
    op.create_table('student-test',
    sa.Column('st_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=255), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('st_id'),
    sa.UniqueConstraint('status')
    )
    op.create_table('test',
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_num', sa.Integer(), nullable=True),
    sa.Column('test_name', sa.String(length=2000), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('test_id')
    )
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('topic_param', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_name'),
    sa.UniqueConstraint('topic_param')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    op.drop_table('test')
    op.drop_table('student-test')
    op.drop_table('student')
    op.drop_table('pool')
    op.drop_table('nonceverify')
    op.drop_table('course')
    # ### end Alembic commands ###
