"""empty message

Revision ID: 9c73bdf2a617
Revises: b33eacc3a220
Create Date: 2020-05-21 20:51:36.560900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c73bdf2a617'
down_revision = 'b33eacc3a220'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('course_name', sa.String(length=500), nullable=False),
    sa.Column('course_param', sa.String(length=500), nullable=False),
    sa.PrimaryKeyConstraint('course_id'),
    sa.UniqueConstraint('course_name'),
    sa.UniqueConstraint('course_param')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('course')
    # ### end Alembic commands ###
