"""empty message

Revision ID: b33eacc3a220
Revises: 176c68c588be
Create Date: 2020-05-21 20:24:10.086502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b33eacc3a220'
down_revision = '176c68c588be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('topic',
    sa.Column('topic_id', sa.Integer(), nullable=False),
    sa.Column('topic_name', sa.String(length=255), nullable=False),
    sa.Column('topic_param', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('topic_id'),
    sa.UniqueConstraint('topic_name'),
    sa.UniqueConstraint('topic_param')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('topic')
    # ### end Alembic commands ###
